"""QC PDF report generation using fpdf2.

Generates branded, engineering-grade QC reports with:
- Executive mode: concise 1-2 page summary for client distribution
- Technical mode: full multi-page report for engineering review
- Statement of Quality with optional triage summary
- Embedded matplotlib charts (severity pie, KP density)
"""

from __future__ import annotations

import io
import tempfile
from collections import Counter, defaultdict

from fpdf import FPDF

from app.services.chart_builder import generate_kp_density_chart, generate_severity_pie


# Brand colors
BRAND_DARK = (15, 23, 42)     # slate-900
BRAND_MID = (51, 65, 85)      # slate-700
BRAND_LIGHT = (148, 163, 184) # slate-400
BRAND_TEAL = (20, 184, 166)   # teal-500
WHITE = (255, 255, 255)
LIGHT_GRAY = (248, 250, 252)  # slate-50
BORDER_GRAY = (226, 232, 240) # slate-200

SEVERITY_COLORS = {
    "critical": (239, 68, 68),    # red-500
    "warning": (245, 158, 11),    # amber-500
    "info": (59, 130, 246),       # blue-500
}

SEVERITY_BG = {
    "critical": (254, 226, 226),  # red-100
    "warning": (254, 243, 199),   # amber-100
    "info": (219, 234, 254),      # blue-100
}

# Check category labels for grouping
CHECK_CATEGORIES = {
    "range_check": "Range Violations",
    "missing_data": "Missing Data",
    "duplicate_row": "Duplicate Rows",
    "near_duplicate_kp": "Near-Duplicate KP",
    "outlier_zscore": "Statistical Outliers (Z-Score)",
    "outlier_iqr": "Statistical Outliers (IQR)",
    "kp_gap": "KP Gaps",
    "monotonicity": "KP Monotonicity",
    "cross_column_consistency": "Cross-Column Consistency",
    "spike_gradient": "Spike Detection (Gradient)",
    "spike_detection": "Spike Detection (MAD)",
    "coordinate_bounds": "Coordinate Bounds",
    "coordinate_jump": "Coordinate Jumps",
}

MAX_ISSUES_IN_PDF = 500


def _sanitize(text: str) -> str:
    """Replace Unicode characters that Helvetica can't encode."""
    return (
        text
        .replace("\u2014", "--")   # em dash
        .replace("\u2013", "-")    # en dash
        .replace("\u2018", "'")    # left single quote
        .replace("\u2019", "'")    # right single quote
        .replace("\u201c", '"')    # left double quote
        .replace("\u201d", '"')    # right double quote
        .replace("\u2264", "<=")   # <=
        .replace("\u2265", ">=")   # >=
        .replace("\u2260", "!=")   # !=
    )


class QCReport(FPDF):
    """Custom FPDF subclass for QC reports."""

    def __init__(self, dataset_name: str = "", report_mode: str = "technical"):
        super().__init__()
        self.set_compression(False)
        self.dataset_name = dataset_name
        self.report_mode = report_mode
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Top bar
        self.set_fill_color(*BRAND_DARK)
        self.rect(0, 0, 210, 12, "F")
        self.set_y(2)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*WHITE)
        if self.report_mode == "executive":
            title = "TruQC  |  QC Summary Report"
        else:
            title = "TruQC  |  QC Technical Report"
        self.cell(0, 8, title, align="C")
        self.set_y(16)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*BRAND_LIGHT)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by TruQC QC Engine", align="C")

    def section_title(self, title: str):
        """Render a section heading."""
        self.ln(4)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*BRAND_DARK)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        # Underline
        self.set_draw_color(*BORDER_GRAY)
        self.line(self.l_margin, self.get_y(), 210 - self.r_margin, self.get_y())
        self.ln(4)

    def kv_row(self, label: str, value: str, bold_value: bool = False, value_color: tuple | None = None):
        """Render a key-value row."""
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*BRAND_MID)
        self.cell(50, 6, _sanitize(label))
        if value_color:
            self.set_text_color(*value_color)
        else:
            self.set_text_color(*BRAND_DARK)
        self.set_font("Helvetica", "B" if bold_value else "", 9)
        self.cell(0, 6, _sanitize(value), new_x="LMARGIN", new_y="NEXT")


def _build_soq_text(
    run_data: dict, dataset_name: str, triage_counts: dict | None = None
) -> str:
    """Build Statement of Quality text paragraph."""
    total = run_data.get("total_issues", 0)
    critical = run_data.get("critical_count", 0)
    pass_rate = run_data.get("pass_rate", 0)
    verdict = "PASS" if critical == 0 else "FAIL"

    text = (
        f"This dataset ({dataset_name}) has been validated by the TruQC automated QC engine "
        f"and received an overall verdict of {verdict} with a pass rate of {pass_rate:.1f}%. "
        f"A total of {total} issues were identified across all check categories."
    )

    if triage_counts and any(v > 0 for v in triage_counts.values()):
        accepted = triage_counts.get("accepted", 0)
        rejected = triage_counts.get("rejected", 0)
        deferred = triage_counts.get("deferred", 0)
        text += (
            f" Of these, {accepted} were accepted for remediation, "
            f"{rejected} were rejected as false positives, "
            f"and {deferred} were deferred for further review."
        )

    return text


def _add_soq_section(
    pdf: QCReport,
    run_data: dict,
    dataset_name: str,
    triage_counts: dict | None = None,
) -> None:
    """Add Statement of Quality section with validated badge."""
    pdf.section_title("Statement of Quality")

    soq_text = _build_soq_text(run_data, dataset_name, triage_counts)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*BRAND_MID)
    pdf.multi_cell(0, 5, _sanitize(soq_text))
    pdf.ln(4)

    # "Validated by TruQC" badge
    badge_x = pdf.l_margin + 30
    badge_y = pdf.get_y()
    badge_w = 120
    badge_h = 22

    pdf.set_draw_color(*BRAND_TEAL)
    pdf.set_line_width(0.8)
    pdf.rect(badge_x, badge_y, badge_w, badge_h)
    pdf.set_line_width(0.2)  # reset

    # Badge text
    pdf.set_xy(badge_x, badge_y + 3)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*BRAND_TEAL)
    pdf.cell(badge_w, 7, "VALIDATED BY TRUQC", align="C")

    # Date and run ref
    pdf.set_xy(badge_x, badge_y + 11)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*BRAND_MID)
    run_date = str(run_data.get("run_at", "N/A"))[:10]
    run_id = str(run_data.get("id", ""))[:8]
    pdf.cell(badge_w, 6, f"Date: {run_date}  |  Ref: {run_id}", align="C")

    pdf.set_y(badge_y + badge_h + 4)


def _add_top_issues(pdf: QCReport, issues: list[dict], n: int = 3) -> None:
    """Add top N issues section (critical-first) for Executive mode."""
    if not issues:
        return

    pdf.section_title("Top Issues")

    # Sort critical first, then warning, then info
    severity_order = {"critical": 0, "warning": 1, "info": 2}
    sorted_issues = sorted(issues, key=lambda x: severity_order.get(x.get("severity", "info"), 2))
    top = sorted_issues[:n]

    for issue in top:
        severity = issue.get("severity", "info")
        sev_color = SEVERITY_COLORS.get(severity, BRAND_DARK)
        row = issue.get("row_number", "?")
        col = _sanitize(str(issue.get("column_name", "unknown")))
        msg = _sanitize(str(issue.get("message", "")))

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*sev_color)
        pdf.cell(0, 6, f"[{severity.upper()}] Row {row}, Column: {col}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*BRAND_MID)
        pdf.multi_cell(0, 4.5, msg)
        pdf.ln(2)


def _embed_chart(pdf: QCReport, chart_img, width: int = 90) -> None:
    """Embed a PIL Image chart into the PDF using a temp file."""
    if chart_img is None:
        return
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        chart_img.save(tmp, format="PNG")
        tmp_path = tmp.name
    pdf.image(tmp_path, x=pdf.l_margin, w=width)
    pdf.ln(3)
    import os
    try:
        os.unlink(tmp_path)
    except OSError:
        pass


def generate_pdf_report(
    run_data: dict,
    issues: list[dict],
    dataset_name: str,
    mode: str = "technical",
    triage_counts: dict | None = None,
) -> bytes:
    """Generate an engineering-grade PDF QC report.

    Args:
        run_data: Validation run metadata.
        issues: List of validation issue dicts.
        dataset_name: Name of the dataset file.
        mode: "executive" for concise summary, "technical" for full report.
        triage_counts: Optional dict with accepted/rejected/deferred counts.
    """
    pdf = QCReport(dataset_name=dataset_name, report_mode=mode)
    pdf.alias_nb_pages()
    pdf.add_page()

    total = run_data.get("total_issues", 0)
    critical = run_data.get("critical_count", 0)
    warnings = run_data.get("warning_count", 0)
    info = run_data.get("info_count", 0)
    pass_rate = run_data.get("pass_rate", 0)
    verdict = "PASS" if critical == 0 else "FAIL"

    # ── Executive Summary (both modes) ────────────────────
    pdf.section_title("Executive Summary")

    # Verdict box
    if verdict == "PASS":
        pdf.set_fill_color(220, 252, 231)  # green-100
        verdict_color = (22, 163, 74)      # green-600
    else:
        pdf.set_fill_color(254, 226, 226)  # red-100
        verdict_color = (220, 38, 38)      # red-600

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*verdict_color)
    y = pdf.get_y()
    pdf.rect(pdf.l_margin, y, 190, 12, "F")
    pdf.cell(0, 12, f"Overall Verdict: {verdict}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.kv_row("Dataset", dataset_name)
    pdf.kv_row("Pass Rate", f"{pass_rate:.1f}%", bold_value=True,
               value_color=(22, 163, 74) if pass_rate >= 90 else (220, 38, 38) if pass_rate < 70 else (245, 158, 11))
    pdf.kv_row("Total Issues", str(total))
    pdf.kv_row("Run Date", str(run_data.get("run_at", "N/A"))[:19])

    # Config snapshot summary
    config = run_data.get("config_snapshot") or {}
    if config:
        enabled = config.get("enabled_checks", {})
        active_checks = sum(1 for v in enabled.values() if v) if enabled else 0
        pdf.kv_row("Active Checks", f"{active_checks} of {len(enabled)}" if enabled else "All (default)")

    pdf.ln(2)

    # ── Severity Pie Chart (both modes) ───────────────────
    pie_img = generate_severity_pie(critical, warnings, info)
    _embed_chart(pdf, pie_img, width=90)

    # ── Executive-only sections ───────────────────────────
    if mode == "executive":
        _add_top_issues(pdf, issues, n=3)
        _add_soq_section(pdf, run_data, dataset_name, triage_counts)
        return pdf.output()

    # ── Technical-only sections below ─────────────────────

    # Severity Breakdown bars
    pdf.section_title("Severity Breakdown")

    severity_data = [
        ("Critical", critical, SEVERITY_COLORS["critical"]),
        ("Warning", warnings, SEVERITY_COLORS["warning"]),
        ("Info", info, SEVERITY_COLORS["info"]),
    ]

    bar_max_width = 120
    max_count = max(critical, warnings, info, 1)

    for label, count, color in severity_data:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*BRAND_DARK)
        pdf.cell(30, 8, label)

        bar_width = (count / max_count) * bar_max_width if max_count > 0 else 0
        y = pdf.get_y() + 1.5
        pdf.set_fill_color(*color)
        if bar_width > 0:
            pdf.rect(pdf.get_x(), y, bar_width, 5, "F")

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*BRAND_MID)
        pdf.cell(bar_max_width + 5, 8, "")
        pdf.cell(0, 8, str(count), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(2)

    # ── Issues by Category ────────────────────────────────
    if issues:
        pdf.section_title("Issues by Check Category")

        category_counts: dict[str, dict[str, int]] = defaultdict(lambda: {"critical": 0, "warning": 0, "info": 0})
        for issue in issues:
            rule = issue.get("rule_type", "unknown")
            severity = issue.get("severity", "info")
            category_counts[rule][severity] += 1

        cat_widths = [70, 25, 25, 25, 25]
        cat_headers = ["Check", "Critical", "Warning", "Info", "Total"]
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(*BRAND_DARK)
        pdf.set_text_color(*WHITE)
        for i, h in enumerate(cat_headers):
            pdf.cell(cat_widths[i], 7, h, border=1, fill=True, align="C" if i > 0 else "L")
        pdf.ln()

        pdf.set_font("Helvetica", "", 8)
        alt = False
        for rule_type, counts in sorted(category_counts.items(), key=lambda x: sum(x[1].values()), reverse=True):
            cat_label = CHECK_CATEGORIES.get(rule_type, rule_type.replace("_", " ").title())
            row_total = sum(counts.values())

            if alt:
                pdf.set_fill_color(*LIGHT_GRAY)
            else:
                pdf.set_fill_color(*WHITE)
            alt = not alt

            pdf.set_text_color(*BRAND_DARK)
            pdf.cell(cat_widths[0], 6, cat_label, border=1, fill=True)

            for sev in ["critical", "warning", "info"]:
                val = counts[sev]
                if val > 0 and sev == "critical":
                    pdf.set_text_color(*SEVERITY_COLORS["critical"])
                    pdf.set_font("Helvetica", "B", 8)
                elif val > 0:
                    pdf.set_text_color(*BRAND_DARK)
                    pdf.set_font("Helvetica", "", 8)
                else:
                    pdf.set_text_color(*BRAND_LIGHT)
                    pdf.set_font("Helvetica", "", 8)
                pdf.cell(cat_widths[1], 6, str(val) if val > 0 else "-", border=1, fill=True, align="C")

            pdf.set_text_color(*BRAND_DARK)
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(cat_widths[4], 6, str(row_total), border=1, fill=True, align="C")
            pdf.ln()

        pdf.ln(2)

    # ── Per-Column Summary ────────────────────────────────
    if issues:
        pdf.section_title("Issues by Column")

        col_counts: dict[str, int] = Counter()
        for issue in issues:
            col = issue.get("column_name", "unknown")
            col_counts[col] += 1

        pdf.set_font("Helvetica", "", 9)
        for col, count in col_counts.most_common(15):
            pdf.set_text_color(*BRAND_MID)
            pdf.cell(50, 6, col)
            pdf.set_text_color(*BRAND_DARK)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, f"{count} issue{'s' if count != 1 else ''}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)

        pdf.ln(2)

    # ── KP Density Chart ──────────────────────────────────
    kp_img = generate_kp_density_chart(issues)
    if kp_img is not None:
        pdf.section_title("KP Density")
        _embed_chart(pdf, kp_img, width=170)
    else:
        pdf.ln(2)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*BRAND_LIGHT)
        pdf.cell(0, 6, "KP density chart unavailable -- no KP data in dataset", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # ── Methodology ───────────────────────────────────────
    pdf.section_title("Methodology")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*BRAND_MID)
    methodology = (
        "This report was generated by the TruQC automated QC engine. "
        "The dataset was validated against engineering-grade checks including:\n\n"
        "Basic QC: Range validation, missing data detection, duplicate row/KP identification, "
        "KP gap analysis, KP monotonicity enforcement, and statistical outlier detection "
        "(z-score and IQR methods).\n\n"
        "Engineering-Grade QC: Cross-column physical consistency checks "
        "(e.g. DOB vs water depth, DOC vs DOB), spike and gradient detection "
        "with KP-aware rate-of-change thresholds, and coordinate sanity validation "
        "including bounds checking and consecutive point jump detection.\n\n"
        "Each flagged issue includes severity level, affected row and column, "
        "and a human-readable explanation of the problem found. "
        "Issues are classified as Critical (data integrity broken), "
        "Warning (suspicious but usable), or Info (informational)."
    )
    pdf.multi_cell(0, 5, methodology)
    pdf.ln(3)

    # ── Statement of Quality ──────────────────────────────
    _add_soq_section(pdf, run_data, dataset_name, triage_counts)

    # ── Detailed Issues Table ─────────────────────────────
    if issues:
        pdf.add_page()
        pdf.section_title(f"Detailed Issues ({min(len(issues), MAX_ISSUES_IN_PDF)} of {len(issues)})")

        display_issues = issues[:MAX_ISSUES_IN_PDF]

        col_widths = [12, 22, 18, 128]
        headers = ["Row", "Column", "Severity", "Description"]
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_fill_color(*BRAND_DARK)
        pdf.set_text_color(*WHITE)
        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 7, header, border=1, fill=True)
        pdf.ln()

        pdf.set_font("Helvetica", "", 7)
        for issue in display_issues:
            severity = str(issue.get("severity", ""))
            fill_color = SEVERITY_BG.get(severity, LIGHT_GRAY)
            pdf.set_fill_color(*fill_color)
            pdf.set_text_color(*BRAND_DARK)

            desc = _sanitize(str(issue.get("message", "")))
            max_desc_chars = 90
            desc_display = desc[:max_desc_chars] + "..." if len(desc) > max_desc_chars else desc

            row_values = [
                str(issue.get("row_number", "")),
                _sanitize(str(issue.get("column_name", "")))[:12],
                severity,
                desc_display,
            ]

            for i, val in enumerate(row_values):
                if i == 2:
                    sev_color = SEVERITY_COLORS.get(severity, BRAND_DARK)
                    pdf.set_text_color(*sev_color)
                    pdf.set_font("Helvetica", "B", 7)
                else:
                    pdf.set_text_color(*BRAND_DARK)
                    pdf.set_font("Helvetica", "", 7)
                pdf.cell(col_widths[i], 5.5, val, border=1, fill=True)
            pdf.ln()

        if len(issues) > MAX_ISSUES_IN_PDF:
            remaining = len(issues) - MAX_ISSUES_IN_PDF
            pdf.ln(3)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(*SEVERITY_COLORS["warning"])
            pdf.cell(
                0, 7,
                f"{remaining} additional issues not shown. Export the annotated dataset for complete results.",
                new_x="LMARGIN", new_y="NEXT",
            )

    return pdf.output()
