"""QC PDF report generation using fpdf2.

Generates branded, engineering-grade QC reports with:
- Executive summary with pass/fail verdict
- Severity breakdown with visual bars
- Issues grouped by check category
- Per-column issue summary
- Detailed issues table
"""

from collections import Counter, defaultdict
from fpdf import FPDF


# Brand colors
BRAND_DARK = (15, 23, 42)     # slate-900
BRAND_MID = (51, 65, 85)      # slate-700
BRAND_LIGHT = (148, 163, 184) # slate-400
WHITE = (255, 255, 255)
LIGHT_GRAY = (248, 250, 252)  # slate-50
BORDER_GRAY = (226, 232, 240) # slate-200

SEVERITY_COLORS = {
    "critical": (239, 68, 68),    # red-500
    "warning": (245, 158, 11),    # amber-500
    "info": (59, 130, 246),       # blue-500
}

SEVERITY_BG = {
    "critical": (254, 226, 226),  # red-100
    "warning": (254, 243, 199),   # amber-100
    "info": (219, 234, 254),      # blue-100
}

# Check category labels for grouping
CHECK_CATEGORIES = {
    "range_check": "Range Violations",
    "missing_data": "Missing Data",
    "duplicate_row": "Duplicate Rows",
    "near_duplicate_kp": "Near-Duplicate KP",
    "outlier_zscore": "Statistical Outliers (Z-Score)",
    "outlier_iqr": "Statistical Outliers (IQR)",
    "kp_gap": "KP Gaps",
    "monotonicity": "KP Monotonicity",
    "cross_column_consistency": "Cross-Column Consistency",
    "spike_gradient": "Spike Detection (Gradient)",
    "spike_detection": "Spike Detection (MAD)",
    "coordinate_bounds": "Coordinate Bounds",
    "coordinate_jump": "Coordinate Jumps",
}

MAX_ISSUES_IN_PDF = 500


def _sanitize(text: str) -> str:
    """Replace Unicode characters that Helvetica can't encode."""
    return (
        text
        .replace("\u2014", "--")   # em dash
        .replace("\u2013", "-")    # en dash
        .replace("\u2018", "'")    # left single quote
        .replace("\u2019", "'")    # right single quote
        .replace("\u201c", '"')    # left double quote
        .replace("\u201d", '"')    # right double quote
        .replace("\u2264", "<=")   # ≤
        .replace("\u2265", ">=")   # ≥
        .replace("\u2260", "!=")   # ≠
    )


class QCReport(FPDF):
    """Custom FPDF subclass for QC reports."""

    def __init__(self, dataset_name: str = ""):
        super().__init__()
        self.set_compression(False)
        self.dataset_name = dataset_name
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Top bar
        self.set_fill_color(*BRAND_DARK)
        self.rect(0, 0, 210, 12, "F")
        self.set_y(2)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*WHITE)
        self.cell(0, 8, "DataFlow  |  QC Validation Report", align="C")
        self.set_y(16)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*BRAND_LIGHT)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by DataFlow QC Engine", align="C")

    def section_title(self, title: str):
        """Render a section heading."""
        self.ln(4)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*BRAND_DARK)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        # Underline
        self.set_draw_color(*BORDER_GRAY)
        self.line(self.l_margin, self.get_y(), 210 - self.r_margin, self.get_y())
        self.ln(4)

    def kv_row(self, label: str, value: str, bold_value: bool = False, value_color: tuple | None = None):
        """Render a key-value row."""
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*BRAND_MID)
        self.cell(50, 6, _sanitize(label))
        if value_color:
            self.set_text_color(*value_color)
        else:
            self.set_text_color(*BRAND_DARK)
        self.set_font("Helvetica", "B" if bold_value else "", 9)
        self.cell(0, 6, _sanitize(value), new_x="LMARGIN", new_y="NEXT")


def generate_pdf_report(
    run_data: dict, issues: list[dict], dataset_name: str
) -> bytes:
    """Generate an engineering-grade PDF QC report."""
    pdf = QCReport(dataset_name=dataset_name)
    pdf.alias_nb_pages()
    pdf.add_page()

    total = run_data.get("total_issues", 0)
    critical = run_data.get("critical_count", 0)
    warnings = run_data.get("warning_count", 0)
    info = run_data.get("info_count", 0)
    pass_rate = run_data.get("pass_rate", 0)
    verdict = "PASS" if critical == 0 else "FAIL"

    # ── Executive Summary ──────────────────────────────────
    pdf.section_title("Executive Summary")

    # Verdict box
    if verdict == "PASS":
        pdf.set_fill_color(220, 252, 231)  # green-100
        verdict_color = (22, 163, 74)      # green-600
    else:
        pdf.set_fill_color(254, 226, 226)  # red-100
        verdict_color = (220, 38, 38)      # red-600

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*verdict_color)
    y = pdf.get_y()
    pdf.rect(pdf.l_margin, y, 190, 12, "F")
    pdf.cell(0, 12, f"Overall Verdict: {verdict}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.kv_row("Dataset", dataset_name)
    pdf.kv_row("Pass Rate", f"{pass_rate:.1f}%", bold_value=True,
               value_color=(22, 163, 74) if pass_rate >= 90 else (220, 38, 38) if pass_rate < 70 else (245, 158, 11))
    pdf.kv_row("Total Issues", str(total))
    pdf.kv_row("Run Date", str(run_data.get("run_at", "N/A"))[:19])

    # Config snapshot summary
    config = run_data.get("config_snapshot") or {}
    if config:
        enabled = config.get("enabled_checks", {})
        active_checks = sum(1 for v in enabled.values() if v) if enabled else 0
        pdf.kv_row("Active Checks", f"{active_checks} of {len(enabled)}" if enabled else "All (default)")

    pdf.ln(2)

    # ── Severity Breakdown ─────────────────────────────────
    pdf.section_title("Severity Breakdown")

    severity_data = [
        ("Critical", critical, SEVERITY_COLORS["critical"]),
        ("Warning", warnings, SEVERITY_COLORS["warning"]),
        ("Info", info, SEVERITY_COLORS["info"]),
    ]

    bar_max_width = 120
    max_count = max(critical, warnings, info, 1)

    for label, count, color in severity_data:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*BRAND_DARK)
        pdf.cell(30, 8, label)

        # Bar
        bar_width = (count / max_count) * bar_max_width if max_count > 0 else 0
        y = pdf.get_y() + 1.5
        pdf.set_fill_color(*color)
        if bar_width > 0:
            pdf.rect(pdf.get_x(), y, bar_width, 5, "F")

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*BRAND_MID)
        pdf.cell(bar_max_width + 5, 8, "")
        pdf.cell(0, 8, str(count), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(2)

    # ── Issues by Category ─────────────────────────────────
    if issues:
        pdf.section_title("Issues by Check Category")

        category_counts: dict[str, dict[str, int]] = defaultdict(lambda: {"critical": 0, "warning": 0, "info": 0})
        for issue in issues:
            rule = issue.get("rule_type", "unknown")
            severity = issue.get("severity", "info")
            category_counts[rule][severity] += 1

        # Table header
        cat_widths = [70, 25, 25, 25, 25]
        cat_headers = ["Check", "Critical", "Warning", "Info", "Total"]
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(*BRAND_DARK)
        pdf.set_text_color(*WHITE)
        for i, h in enumerate(cat_headers):
            pdf.cell(cat_widths[i], 7, h, border=1, fill=True, align="C" if i > 0 else "L")
        pdf.ln()

        # Table rows
        pdf.set_font("Helvetica", "", 8)
        alt = False
        for rule_type, counts in sorted(category_counts.items(), key=lambda x: sum(x[1].values()), reverse=True):
            cat_label = CHECK_CATEGORIES.get(rule_type, rule_type.replace("_", " ").title())
            row_total = sum(counts.values())

            if alt:
                pdf.set_fill_color(*LIGHT_GRAY)
            else:
                pdf.set_fill_color(*WHITE)
            alt = not alt

            pdf.set_text_color(*BRAND_DARK)
            pdf.cell(cat_widths[0], 6, cat_label, border=1, fill=True)

            for sev in ["critical", "warning", "info"]:
                val = counts[sev]
                if val > 0 and sev == "critical":
                    pdf.set_text_color(*SEVERITY_COLORS["critical"])
                    pdf.set_font("Helvetica", "B", 8)
                elif val > 0:
                    pdf.set_text_color(*BRAND_DARK)
                    pdf.set_font("Helvetica", "", 8)
                else:
                    pdf.set_text_color(*BRAND_LIGHT)
                    pdf.set_font("Helvetica", "", 8)
                pdf.cell(cat_widths[1], 6, str(val) if val > 0 else "-", border=1, fill=True, align="C")

            pdf.set_text_color(*BRAND_DARK)
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(cat_widths[4], 6, str(row_total), border=1, fill=True, align="C")
            pdf.ln()

        pdf.ln(2)

    # ── Per-Column Summary ─────────────────────────────────
    if issues:
        pdf.section_title("Issues by Column")

        col_counts: dict[str, int] = Counter()
        for issue in issues:
            col = issue.get("column_name", "unknown")
            col_counts[col] += 1

        # Compact list
        pdf.set_font("Helvetica", "", 9)
        for col, count in col_counts.most_common(15):
            pdf.set_text_color(*BRAND_MID)
            pdf.cell(50, 6, col)
            pdf.set_text_color(*BRAND_DARK)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, f"{count} issue{'s' if count != 1 else ''}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)

        pdf.ln(2)

    # ── Methodology ────────────────────────────────────────
    pdf.section_title("Methodology")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*BRAND_MID)
    methodology = (
        "This report was generated by the DataFlow automated QC engine. "
        "The dataset was validated against engineering-grade checks including:\n\n"
        "Basic QC: Range validation, missing data detection, duplicate row/KP identification, "
        "KP gap analysis, KP monotonicity enforcement, and statistical outlier detection "
        "(z-score and IQR methods).\n\n"
        "Engineering-Grade QC: Cross-column physical consistency checks "
        "(e.g. DOB vs water depth, DOC vs DOB), spike and gradient detection "
        "with KP-aware rate-of-change thresholds, and coordinate sanity validation "
        "including bounds checking and consecutive point jump detection.\n\n"
        "Each flagged issue includes severity level, affected row and column, "
        "and a human-readable explanation of the problem found. "
        "Issues are classified as Critical (data integrity broken), "
        "Warning (suspicious but usable), or Info (informational)."
    )
    pdf.multi_cell(0, 5, methodology)
    pdf.ln(3)

    # ── Detailed Issues Table ──────────────────────────────
    if issues:
        pdf.add_page()
        pdf.section_title(f"Detailed Issues ({min(len(issues), MAX_ISSUES_IN_PDF)} of {len(issues)})")

        display_issues = issues[:MAX_ISSUES_IN_PDF]

        # Table header
        col_widths = [12, 22, 18, 128]
        headers = ["Row", "Column", "Severity", "Description"]
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_fill_color(*BRAND_DARK)
        pdf.set_text_color(*WHITE)
        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 7, header, border=1, fill=True)
        pdf.ln()

        # Table rows
        pdf.set_font("Helvetica", "", 7)
        for issue in display_issues:
            severity = str(issue.get("severity", ""))
            fill_color = SEVERITY_BG.get(severity, LIGHT_GRAY)
            pdf.set_fill_color(*fill_color)
            pdf.set_text_color(*BRAND_DARK)

            desc = _sanitize(str(issue.get("message", "")))
            max_desc_chars = 90
            desc_display = desc[:max_desc_chars] + "..." if len(desc) > max_desc_chars else desc

            row_values = [
                str(issue.get("row_number", "")),
                _sanitize(str(issue.get("column_name", "")))[:12],
                severity,
                desc_display,
            ]

            # Severity color for severity cell
            for i, val in enumerate(row_values):
                if i == 2:  # severity column
                    sev_color = SEVERITY_COLORS.get(severity, BRAND_DARK)
                    pdf.set_text_color(*sev_color)
                    pdf.set_font("Helvetica", "B", 7)
                else:
                    pdf.set_text_color(*BRAND_DARK)
                    pdf.set_font("Helvetica", "", 7)
                pdf.cell(col_widths[i], 5.5, val, border=1, fill=True)
            pdf.ln()

        if len(issues) > MAX_ISSUES_IN_PDF:
            remaining = len(issues) - MAX_ISSUES_IN_PDF
            pdf.ln(3)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(*SEVERITY_COLORS["warning"])
            pdf.cell(
                0, 7,
                f"{remaining} additional issues not shown. Export the annotated dataset for complete results.",
                new_x="LMARGIN", new_y="NEXT",
            )

    return pdf.output()
