"""QC PDF report generation using fpdf2."""

from fpdf import FPDF


# Brand colors
DEEP_BLUE = (30, 58, 138)  # #1E3A8A
WHITE = (255, 255, 255)
LIGHT_GRAY = (245, 245, 245)
SEVERITY_COLORS = {
    "critical": (255, 204, 204),  # #FFCCCC
    "warning": (255, 255, 204),   # #FFFFCC
    "info": (204, 229, 255),      # #CCE5FF
}

MAX_ISSUES_IN_PDF = 500


class QCReport(FPDF):
    """Custom FPDF subclass for QC reports."""

    def __init__(self, dataset_name: str = ""):
        super().__init__()
        self.set_compression(False)
        self.dataset_name = dataset_name

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*DEEP_BLUE)
        self.cell(0, 10, "QC Validation Report", new_x="LMARGIN", new_y="NEXT", align="C")
        if self.dataset_name:
            self.set_font("Helvetica", "", 10)
            self.set_text_color(100, 100, 100)
            self.cell(0, 6, self.dataset_name, new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def generate_pdf_report(
    run_data: dict, issues: list[dict], dataset_name: str
) -> bytes:
    """Generate a PDF QC report.

    Args:
        run_data: Dict with validation_runs columns (total_issues, critical_count, etc.)
        issues: List of dicts with validation_issues columns.
        dataset_name: Display name for the dataset.

    Returns:
        PDF file content as bytes.
    """
    pdf = QCReport(dataset_name=dataset_name)
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- Summary Section ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*DEEP_BLUE)
    pdf.cell(0, 10, "Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    verdict = "PASS" if run_data.get("critical_count", 0) == 0 else "FAIL"
    verdict_color = (0, 128, 0) if verdict == "PASS" else (200, 0, 0)

    summary_rows = [
        ("Dataset", dataset_name),
        ("Overall Verdict", verdict),
        ("Total Issues", str(run_data.get("total_issues", 0))),
        ("Critical", str(run_data.get("critical_count", 0))),
        ("Warnings", str(run_data.get("warning_count", 0))),
        ("Info", str(run_data.get("info_count", 0))),
        ("Pass Rate", f"{run_data.get('pass_rate', 0):.1f}%"),
        ("Run Date", str(run_data.get("run_at", "N/A"))),
    ]

    pdf.set_font("Helvetica", "", 10)
    for label, value in summary_rows:
        pdf.set_text_color(*DEEP_BLUE)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(50, 7, label, border=1)
        if label == "Overall Verdict":
            pdf.set_text_color(*verdict_color)
            pdf.set_font("Helvetica", "B", 10)
        else:
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, value, border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # --- Methodology Section ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*DEEP_BLUE)
    pdf.cell(0, 10, "Methodology", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(0, 0, 0)
    methodology_text = (
        "This report was generated by the SurveyQC automated validation engine. "
        "The dataset was checked against configured validation rules including "
        "range checks, outlier detection (z-score and IQR methods), KP gap analysis, "
        "duplicate detection, and data completeness checks. Each flagged issue "
        "includes the severity level, affected row and column, and a human-readable "
        "description of the problem found."
    )
    pdf.multi_cell(0, 5, methodology_text)
    pdf.ln(5)

    # --- Issues Table ---
    if issues:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(*DEEP_BLUE)
        pdf.cell(0, 10, "Issues", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        total_issues = len(issues)
        display_issues = issues[:MAX_ISSUES_IN_PDF]

        # Table header
        col_widths = [15, 25, 20, 25, 105]
        headers = ["Row", "Column", "Severity", "Rule", "Description"]
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(*DEEP_BLUE)
        pdf.set_text_color(*WHITE)
        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 7, header, border=1, fill=True)
        pdf.ln()

        # Table rows
        pdf.set_font("Helvetica", "", 7)
        for idx, issue in enumerate(display_issues):
            severity = str(issue.get("severity", ""))
            fill_color = SEVERITY_COLORS.get(severity, LIGHT_GRAY)
            pdf.set_fill_color(*fill_color)
            pdf.set_text_color(0, 0, 0)

            row_values = [
                str(issue.get("row_number", "")),
                str(issue.get("column_name", "")),
                severity,
                str(issue.get("rule_type", "")),
                str(issue.get("message", "")),
            ]

            for i, val in enumerate(row_values):
                # Truncate long descriptions to fit cell
                max_chars = col_widths[i] // 2
                display_val = val[:max_chars] if len(val) > max_chars else val
                pdf.cell(col_widths[i], 6, display_val, border=1, fill=True)
            pdf.ln()

        # Truncation note
        if total_issues > MAX_ISSUES_IN_PDF:
            remaining = total_issues - MAX_ISSUES_IN_PDF
            pdf.ln(3)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(150, 0, 0)
            pdf.cell(
                0, 7,
                f"{remaining} additional issues not shown. "
                "Export full dataset for complete results.",
                new_x="LMARGIN", new_y="NEXT",
            )

    return pdf.output()
